name: stringr
description: Comprehensive string manipulation plugin for dart. Handles operations on latin, non latin and grapheme clusters alike! Features inspured from VocaJs
version: 1.2.1
homepage: https://github.com/Chinmay-KB/stringr

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.3.0
dev_dependencies:
  test: ^1.26.3

dependency_overrides:
  file: ^7.0.1
  watcher: ^1.1.2
